spring.application.name=backend

server.port=${PORT:8080}

# Database Connection
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# --- SAFARICOM DARAJA SANDBOX CONFIGURATION ---
safaricom.mpesa.env=sandbox
safaricom.mpesa.oauth-endpoint=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
mpesa.consumer-key=UrtXNWbDV1BJOjVNjPCSRATGacy3WnAkmIT114gt3thp2iMc
mpesa.consumer-secret=5Z5rwXcLGi3cCeldDpRMbKRy4qG4rFj03hJTWoQvbDLMTTLxxxC9wOJKw9ztn0AU


# STK Push (Inbound Money)
safaricom.mpesa.stk.endpoint=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
safaricom.mpesa.stk.shortcode=174379
safaricom.mpesa.stk.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.base-url=https://sandbox.safaricom.co.ke
safaricom.mpesa.c2b.result-url=https://orderlyserver-production.up.railway.app/api/v1/payments/mpesa/callback
safaricom.mpesa.c2b.queue-timeout-url=https://orderlyserver-production.up.railway.app/api/v1/payments/mpesa/callback

# B2C (Outbound Money)
safaricom.mpesa.b2c.endpoint=https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
safaricom.mpesa.b2c.shortcode=600981
safaricom.mpesa.b2c.initiator-name=testapi
safaricom.mpesa.b2c.security-credential=IfWYTQ4mOfGqForZpFhABCYNx30Ap8NfC9IM9MDAFY6sX31HnKBzfw85dwNouqBS6SPjkH4DeZzCkOVJikr122/1+prxWlo+PBcPSaD2E2w+MfmiUeTpGqVOHIl73i8mktii0P3nvPb92WqbAwxHNHsyWNNF6iWFD6NXZWIj0tlxxH3mBhCwlOavFhBOOqi/mAgZPs6fdiTSiIWa0fwf8+Y5xHOV3bFzJCJcyO4dmcUypScd4LNO6kccNK3rvVsdg6epYJMv8G65Nx3JUYuD2FWjaefgPCmuE6yBh/jo3ZFsNWU+5ALT+J0EgzCB2FHfqtVvR7mU2758E9Sf5ffBFQ==
safaricom.mpesa.b2c.result-url=https://orderlyserver-production.up.railway.app/api/v1/mpesa/b2c/result
safaricom.mpesa.b2c.queue-timeout-url=https://orderlyserver-production.up.railway.app/api/v1/mpesa/b2c/result

# Redis Connection
spring.data.redis.host=${REDISHOST:localhost}
spring.data.redis.port=${REDISPORT:6379}
spring.data.redis.password=${REDISPASSWORD:}

# Lettuce Connection Pool Settings (Industry Standard Defaults)
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=2000ms

# Generate a secure 256-bit (32 byte) base64 encoded string for production.
# For this sprint, use this dummy key:
jwt.secret=${JWT_SECRET_KEY:your_local_secret_key_here}
jwt.refresh-token.expiration=604800000
# Token valid for 24 hours (in milliseconds)
jwt.expiration=86400000

marketplace.fees.platform-percentage=0.10
marketplace.fees.delivery-percentage=0.08

cloud.s3.access-key=acf01260e95d0eecd839012f95eb1ad8
cloud.s3.secret-key=52926b9f446ed9e0b5d9a205b143835e6ced532b2789ae5fc0c31af310bd6e3a
cloud.s3.region=us-east-1
cloud.s3.endpoint=https://75b3bd9c77434d3ecd133c1cdd657e50.r2.cloudflarestorage.com
cloud.s3.bucket-name=marketplacebucket
cloud.s3.public-domain=https://pub-18226c52163e403c8dada99d86a7dd49.r2.dev

#docker command to get inside docker db
#docker exec -it  postgres_db psql -U sa -d marketplaceDB
